### ISSUE TITLE
Error when checking in memcached module

### ISSUE THREAD

**Issue by nzakas** [3rd-Eden/node-hashring#24]
I've been working on a project using the memcached module (v2.0.0) and have been running into problems with hashring. We check our `node_modules` folder into git, and for some reason, whatever build artifacts are created when hashring is built do not end up in `node_modules`. The result is that anyone who clones the repo is met with a "cannot find binding" error for hashring when they try running the project (all developers have the exact same dev-vm setup).

When we used a previous version of the memcached module (0.2.8), this setup worked fine.

Is this something that can be fixed?

**Comment by 3rd-Eden** [comment]
Resolved in latest release.
