### ISSUE TITLE
Changelog for version 3.1.1

### ISSUE THREAD

**Issue by tuxinaut** [3rd-Eden/node-hashring#34]
It'd be nice to have a changelog for version 3.1.1.

**Comment by 3rd-Eden** [comment]
Done, the change was replica's can no longer be set to 0 as that breaks the hashring.

**Comment by tuxinaut** [comment]
Sorry to be a bean counter. The current line for the 3.1.1 changelog is ```Unknown, 2015 (3.1.0)``` but it should be ```Unknown, 2015 (3.1.1)``` or?
