### ISSUE TITLE
Saving/Restoring the Hash Ring

### ISSUE THREAD

**Issue by gavinmcnair** [3rd-Eden/node-hashring#40]
Is there some way to save/reload the initialised hash rings.

I have an implementation which creates the hash rings in the same way each time which takes a second or two per hash ring. If i could dump the created ring (and store it in something like Redis) and load it again when required it would make it much more useful.

**Comment by 3rd-Eden** [comment]
Why would it be more useful? Keys are always hashed the same way. That's the consistent part of the hashring. So loading and saving makes no sense except to save some CPU cycles.

**Comment by gavinmcnair** [comment]
Because I'm using the hash rings for ab testing and i have hundreds of hash rings each for a different ab test after restarting the server each time someone visits each variety of abtest for the first time i have to initialise the associated ring (or spend ages pre-initialising them). Once they are loaded its no bother but on restarting i get about lots of blocking while loading the rings. If i could serialise them i could preload them all. If i scaled to 4000,5000 tests it would block the server for a long time. Unless you can think of a better way :)

**Comment by gavinmcnair** [comment]
Found better deterministic method for ab testing. This is no longer an issue
